### ISSUE TITLE
New Custom Channel Colors getting shuffled after removing/adding Musician [Bug] 

### ISSUE THREAD

**Issue by CrazyMaze10101** [LenweSaralonde/Musician#83] opened 2022-08-23 00:35 UTC
### Description

I change the colors of my text channels, as I have quite a few communities I'm in, and would love to be able to not have them all a peach color (to prevent speaking in the wrong chats)

![Correct](https://user-images.githubusercontent.com/108965513/186039582-b35e9832-a48f-4c68-83fb-fecdc38a9f95.png)

### Reproduction steps

1.) Change the chat channel colors to be anything. The default is 255, 192, 192 (a light red, or as I call it, a peach color. You can use GRM to get exact hex codes)
2.) Go to your addons, and turn on or off Musician
3.) After a reload, the colors should either shuffle, or go up a slot or 2. It will only do this once. (Note: scratch the "only once." As I was trying to confirm if TRP3 had this effect to triple check, I enabled all addons again, NOT changing any colors, and all the colors got randomized)
3.5.) You can also exit game completely (and wait for character to de-load) to get this effect.

Extra info: Changing the colors, exiting game, waiting a couple minutes to de-load my toon, and then logging back in without changing any addons (I had all enabled), seems to shuffle the colors as well. Also, it is specifically the channels tab under chat settings, I am not having this issue with my chat tab (made Officer chat darker green), either because it's only the 1 custom color, or the chat tab isn't affected since there is the custom musician chat in the channel tab. I have also painstakingly gone through all my addons and confirmed it was just musician. I did these steps with the TRP3 as it has a custom channel, and it hasn't 

### Actual behavior

My channel colors are getting moved around, not to where I want them. For ex: I want Trade Services to be Red, and General to be a darker peach color, but when I reload, my Trade becomes dark peach, Newcomer 50/50 becomes the default color of peach, and one of my community chats becomes pure red. Or in the case of the 2nd image named "Wrong Again", a complete scramble.

![Wrong](https://user-images.githubusercontent.com/108965513/186040302-ea3a4113-57b2-489d-acf2-301fe0513d41.png)
![Wrong Again](https://user-images.githubusercontent.com/108965513/186041110-35bb9521-0823-4f90-afe8-709656032f0a.png)

### Expected behavior

Being able to change my channel colors to the colors I want them to be and not shuffled/move up as if in a line for icecream.

### World of Warcraft flavor

Retail

### World of Warcraft version

9.2.7.45114

### Add-on version

1.9.1.0

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

Yes

### Additional context

Unsure if changing just 1 or a few colors will trigger this issue, I tested only by coloring all channels. I haven't been able to consistently get the colors to shuffle or change after changing the colors again 9hence why it's normally a "does it once" thing). I also made sure to change the colors with only TRP3 active, as a way of making sure it wasn't that addon as well, and thus I didn't have GRM enabled to use the hex codes.
After disabling TRP3 and enabling musician, the reload after shuffled all my colors again, so no, it's not because I used hex numbers to color my channels either. I suggested it earlier as that if you want it to continue to be peach after testing, you could easily make it default without using the "chat setting default" button which.., I pressed, and it sucked to re-do all my chat stuff.

**Comment by LenweSaralonde** [comment] 2022-08-23 08:00
TRP3 and Musician use the exact same logic to keep their communication channels at the end so it doesn’t mess up with your own custom channels.
However, the logic for the coloring might be handled separately which might cause this issue. In addition, I personally encounter some issues with the NewcomerChat that keeps moving to position 1, regardless if I use add-ons or not.
I’ll do more tests on my side and see if I can fix it.

**Comment by CrazyMaze10101** [comment] 2022-08-23 23:53
Sorry I'm just now replying, I had kind of forgotten about this. My colors, even after not touching my channel colors, and having all my addons on, are still being randomized. My trade earlier was purple, but now it's red, so I guess it doesn't just change once, perhaps I just wasn't waiting for my character to de-load

**Comment by LenweSaralonde** [comment] 2022-08-24 09:19
The custom colors are not linked to channel names but channel indexes. Musician joins its communication channel very early in the player login process, sometimes before joining any other channel (General, Trade etc) which may result in the colors being shifted, even after logging out my character "properly" (no alt+F4 etc).

I tried delaying the channel joining process and it seems to fix the problem but I won't guarantee that it will work 100% of the times because the way Blizzard handles chat channels always have been a bit messy. In addition, some other add-ons also have their own way of joining and reordering their own channel which can also cause side effects.

**Comment by LenweSaralonde** [comment] 2022-08-25 11:16
@CrazyMaze10101 Could you please try on your side if the problem has been fixed using [this version](https://github.com/LenweSaralonde/Musician/archive/bde2286639bdc4cee32d71191dc547ecce1a22c7.zip) ? (Don't forget to rename the folder into `Musician` and overwrite your current Musician installation if you download it from the ZIP archive)

**Comment by LenweSaralonde** [comment] 2022-08-25 23:08
@CrazyMaze10101 Could you please test using the [latest patchset](https://github.com/LenweSaralonde/Musician/tree/680caba3b739b473cda4cff14f9c721b99d957bc) ?
Be sure to rename the folder from the zip file into Musician to overwrite your existing Musician installation and to disable all your other add-ons (Total RP has a similar problem and may interfere).

**Comment by CrazyMaze10101** [comment] 2022-08-26 03:02
Ok, I'll test it now, ty. I'll see how it works here soon

**Comment by CrazyMaze10101** [comment] 2022-08-26 04:13
I had my channels all in pastel rainbow order for the test. So, for my first reset, my orange went all the way down to the bottom, which is Musician chat, but everything else is all good and in the same order it was originally in. 2nd login, same thing.
And then, when I changed ONLY the musician chat after everything else was scrambled, it did it again? Everything but my 1 channel moved up, so now I had my yellow in musician spot, and the white that I had changed it to is now in my 10 spot. So far, only Newcomer hasn't changed (and it's my 1 spot).
My last test is going to be, changing my colors to the desired colors, except back 1 spot. It worked, but I am unsure if this will be a permanent stick, not to mention I do not have TRP3 on as well, so hopefully it doesn't break if/when I turn it on.

**Comment by LenweSaralonde** [comment] 2022-08-26 08:19
> my orange went all the way down to the bottom, which is Musician chat, but everything else is all good and in the same order it was originally in. 

This is expected behavior. 

The MusicianComm channel is temporary channel, which means its channel number is not persistent and may change at the next login. In addition, channel colors are bound to channel numbers. Let's say you have MusicianComm at position 7 with color red and have green for position 8. In your next session, you might end up with MusicianComm set to position 8 with color green. This is a bit counter-intuitive but this is the way Blizzard implemented chat colors and unfortunately, we can't do anything about it. 😕

Please keep in mind that most add-ons, including Musician, automatically move their chat channels to the end so it doesn't clutter up your regular channels. If you move MusicianComm among your regular chat channels you use for actually chatting, you may end up with some channel numbers and colors being messed up the next time you login. 

Also, please avoid gaps between channels because add-ons channels have their position automatically set and they may end up in gaps, then bubble up to the end which may shuffle colors as well.

> So far, only Newcomer hasn't changed (and it's my 1 spot).

The NewcomerChat bug occurs when it's the first channel to be actually joined at login and it's not at position 1. Yours is at position 1 so you're not affected but I usually put mine at position 5 and it used to change all the time because of this bug which is very annoying.

> I do not have TRP3 on as well, so hopefully it doesn't break if/when I turn it on.

Unfortunately, the channel joining logic was copy-pasted from TRP3 so this TRP3 is affected too. The good news is I managed to fix it as well, the same way I fixed Musician and it seems to work fine now. I'll raise a ticket and open a PR on their project to have it fixed for everyone.

**Comment by CrazyMaze10101** [comment] 2022-08-27 00:09
Ok, so since it seems impossible to have my musician chat at 2 instead, and no way to leave it, my only choice is to deal with the color changes, have all my channel colors the same, or delete musician (And possibly TRP3 as well)? If so, then I'll just consider this closed if there doesn't seem to be a fix, I don't want you to have to work a ton just for a quality-of-life thing most others don't care about and most likely wouldn't encounter.

**Comment by LenweSaralonde** [comment] 2022-08-27 11:42
The addon channels for Musician, TRP and other addons are not intended to be used for chatting so you don"t have to bother setting a color for them and they should remain at the end of the list.

What you can do (when the fixed version of Musician and TRP are available) is to set rainbow colors to your permanent channels and leave the default color for the addon channels that remain at the end of the list.

**Comment by LenweSaralonde** [comment] 2022-08-27 17:59
The fix has been implemented into TRP3 as well.

**Closed as completed by LenweSaralonde** 2022-08-27 17:59 UTC
Labels: bug
